import path from 'path';
import fs from 'fs';
import sharp from 'sharp';
import metaPngPkg from 'meta-png';
const { addMetadata, getMetadata } = metaPngPkg;
import { globSync } from 'glob';
import { wasScreenshotUsed } from './screenshotPath.utils';
import { METADATA_KEY } from './constants';

// version of images generated by this plugin
// bump only when there is a breaking change to:
// image comparison or image generation algorithms
const DIFF_IMAGES_VERSION = '1';

type PluginMetadata = {
  version: string;
  testingType?: 'e2e' | 'component';
};

type PluginMetadataConfig = {
  testingType?: string;
};

export const addPNGMetadata = (config: PluginMetadataConfig, png: Buffer) =>
  addMetadata(
    new Uint8Array(png),
    METADATA_KEY,
    JSON.stringify({
      version: DIFF_IMAGES_VERSION,
      testingType: config.testingType || 'e2e',
    } as PluginMetadata) /* c8 ignore next */,
  );
export const getPNGMetadata = (png: Buffer): PluginMetadata | undefined => {
  const metadataString = getMetadata(
    new Uint8Array(png),
    METADATA_KEY /* c8 ignore next */,
  );
  if (metadataString === undefined) return;
  try {
    return JSON.parse(metadataString);
  } catch /* v8 ignore next 2 */ {
    return { version: metadataString };
  }
};
export const isImageCurrentVersion = (png: Buffer) =>
  getPNGMetadata(png)?.version === DIFF_IMAGES_VERSION;
export const isImageGeneratedByPlugin = (png: Buffer) =>
  !!getPNGMetadata(png /* c8 ignore next */);
export const isImageOfTestType = (
  png: Buffer,
  testingType?: PluginMetadataConfig['testingType'],
) => {
  if (!isImageGeneratedByPlugin(png)) return false;
  const imageTestingType = getPNGMetadata(
    png /* c8 ignore next */,
  )?.testingType;
  return imageTestingType === testingType || testingType === undefined;
};

export const writePNG = (
  config: PluginMetadataConfig,
  name: string,
  png: Buffer,
) => fs.writeFileSync(name, addPNGMetadata(config, png));

export type ImageInfo = { width: number; height: number };

// decodes a PNG to 8-bit RGBA pixels (what pixelmatch expects)
export const decodePNG = async (png: Buffer) => {
  const { data, info } = await sharp(png)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return {
    data,
    info: { width: info.width, height: info.height } as ImageInfo,
  };
};

// encodes 8-bit RGBA pixels to PNG
export const encodePNG = (raw: Buffer, { width, height }: ImageInfo) =>
  sharp(raw, { raw: { width, height, channels: 4 } })
    .png()
    .toBuffer();

// extends the image canvas to width x height (anchored top-left) and
// returns 8-bit RGBA pixels; the added area is filled with translucent black
export const padImageToSize = (
  png: Buffer,
  info: ImageInfo,
  { width, height }: ImageInfo,
) =>
  sharp(png)
    .ensureAlpha()
    .extend({
      right: width - info.width,
      bottom: height - info.height,
      background: { r: 0, g: 0, b: 0, alpha: 64 / 255 },
    })
    .raw()
    .toBuffer();

export const scaleImageAndWrite = async ({
  scaleFactor,
  path,
}: {
  scaleFactor: number;
  path: string;
}) => {
  const imgBuffer = fs.readFileSync(path);
  if (scaleFactor === 1) return imgBuffer;

  const { width, height } = await sharp(imgBuffer).metadata();
  const newImageWidth = Math.ceil(width * scaleFactor);
  const newImageHeight = Math.ceil(height * scaleFactor);
  await sharp(imgBuffer).resize(newImageWidth, newImageHeight).toFile(path);

  return fs.readFileSync(path);
};

export const cleanupUnused = (
  config: PluginMetadataConfig & { projectRoot: string },
) => {
  globSync('**/*.png', {
    cwd: config.projectRoot,
    ignore: 'node_modules/**/*',
  }).forEach((pngPath) => {
    const absolutePath = path.join(config.projectRoot, pngPath);
    if (
      !wasScreenshotUsed(pngPath) &&
      isImageOfTestType(fs.readFileSync(absolutePath), config.testingType)
    ) {
      fs.unlinkSync(absolutePath);
    }
  });
};
