import path from 'path';
import fs from 'fs';
import sharp from 'sharp';
import metaPngPkg from 'meta-png';
const { addMetadata, getMetadata } = metaPngPkg;
import { globSync } from 'glob';
import { wasScreenshotUsed } from './screenshotPath.utils';
import { METADATA_KEY } from './constants';

// version of images generated by this plugin
// bump only when there is a breaking change to:
// image comparison or image generation algorithms
const DIFF_IMAGES_VERSION = '1';

type PluginMetadata = {
  version: string;
  testingType?: 'e2e' | 'component';
};

type PluginMetadataConfig = {
  testingType?: string;
};

export const addPNGMetadata = (config: PluginMetadataConfig, png: Buffer) => {
  const stamped = addMetadata(
    new Uint8Array(png),
    METADATA_KEY,
    JSON.stringify({
      version: DIFF_IMAGES_VERSION,
      testingType: config.testingType || 'e2e',
    } as PluginMetadata) /* c8 ignore next */,
  );
  // view over the same memory, no copy
  return Buffer.from(stamped.buffer, stamped.byteOffset, stamped.byteLength);
};
export const getPNGMetadata = (png: Buffer): PluginMetadata | undefined => {
  const metadataString = getMetadata(
    new Uint8Array(png),
    METADATA_KEY /* c8 ignore next */,
  );
  if (metadataString === undefined) return;
  try {
    return JSON.parse(metadataString);
  } catch /* v8 ignore next 2 */ {
    return { version: metadataString };
  }
};
export const isImageCurrentVersion = (png: Buffer) =>
  getPNGMetadata(png)?.version === DIFF_IMAGES_VERSION;
export const isImageGeneratedByPlugin = (png: Buffer) =>
  !!getPNGMetadata(png /* c8 ignore next */);
export const isImageOfTestType = (
  png: Buffer,
  testingType?: PluginMetadataConfig['testingType'],
) => {
  const metadata = getPNGMetadata(png /* c8 ignore next */);
  return (
    !!metadata &&
    (testingType === undefined || metadata.testingType === testingType)
  );
};

export type ImageInfo = { width: number; height: number };

// reads the dimensions from the PNG header, without decoding pixels
export const getImageSize = async (png: Buffer): Promise<ImageInfo> => {
  const { width, height } = await sharp(png).metadata();
  return { width, height };
};

// decodes a PNG to 8-bit RGBA pixels (what pixelmatch expects); when `size` is
// larger than the image, the canvas is extended (anchored top-left) and the
// added area is filled with translucent black
export const decodePNG = (
  png: Buffer,
  imageSize: ImageInfo,
  size: ImageInfo = imageSize,
) =>
  sharp(png)
    .ensureAlpha()
    .extend({
      right: size.width - imageSize.width,
      bottom: size.height - imageSize.height,
      background: { r: 0, g: 0, b: 0, alpha: 64 / 255 },
    })
    .raw()
    .toBuffer();

// encodes 8-bit RGBA pixels to PNG
export const encodePNG = (raw: Buffer, { width, height }: ImageInfo) =>
  sharp(raw, { raw: { width, height, channels: 4 } })
    .png()
    .toBuffer();

export const scaleImage = async (png: Buffer, scaleFactor: number) => {
  if (scaleFactor === 1) return png;

  const image = sharp(png);
  const { width, height } = await image.metadata();
  return image
    .resize(Math.ceil(width * scaleFactor), Math.ceil(height * scaleFactor))
    .toBuffer();
};

export const cleanupUnused = (
  config: PluginMetadataConfig & { projectRoot: string },
) => {
  globSync('**/*.png', {
    cwd: config.projectRoot,
    ignore: 'node_modules/**/*',
  }).forEach((pngPath) => {
    const absolutePath = path.join(config.projectRoot, pngPath);
    if (
      !wasScreenshotUsed(pngPath) &&
      isImageOfTestType(fs.readFileSync(absolutePath), config.testingType)
    ) {
      fs.unlinkSync(absolutePath);
    }
  });
};
